### ISSUE TITLE
NetBSD support

### ISSUE THREAD

**Issue by woelper** [Byron/trash-rs#83] opened 2023-09-16 20:56 UTC
I know that this is probably an exotic target, but when I build this library for NetBSD, I get the following error:

```
      Checking trash v3.0.6
  error[E0412]: cannot find type `statfs` in crate `libc`
     --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trash-3.0.6/src/freedesktop.rs:703:34
      |
  703 |       let mut fs_infos: *mut libc::statfs = std::ptr::null_mut();
      |                                    ^^^^^^ help: a struct with a similar name exists: `statvfs`
      |
     ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.148/src/unix/bsd/netbsdlike/netbsd/mod.rs:757:1
      |
  757 | / s_no_extra_traits! {
  758 | |
  759 | |     pub struct utmpx {
  760 | |         pub ut_name: [::c_char; _UTX_USERSIZE],
  ...   |
  878 | |     }
  879 | | }
      | |_- similarly named struct `statvfs` defined here
  
  error[E0425]: cannot find function `getmntinfo` in crate `libc`
     --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trash-3.0.6/src/freedesktop.rs:704:32
      |
  704 |     let count = unsafe { libc::getmntinfo(&mut fs_infos, libc::MNT_WAIT) };
      |                                ^^^^^^^^^^ not found in `libc`
  
  error[E0425]: cannot find value `MNT_WAIT` in crate `libc`
     --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trash-3.0.6/src/freedesktop.rs:704:64
      |
  704 |     let count = unsafe { libc::getmntinfo(&mut fs_infos, libc::MNT_WAIT) };
      |                                                                ^^^^^^^^ not found in `libc`
  
  error[E0412]: cannot find type `statfs` in crate `libc`
     --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trash-3.0.6/src/freedesktop.rs:708:27
      |
  708 |       let fs_infos: &[libc::statfs] = unsafe { std::slice::from_raw_parts(fs_infos as _, count as _) };
      |                             ^^^^^^ help: a struct with a similar name exists: `statvfs`
      |
     ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.148/src/unix/bsd/netbsdlike/netbsd/mod.rs:757:1
      |
  757 | / s_no_extra_traits! {
  758 | |
  759 | |     pub struct utmpx {
  760 | |         pub ut_name: [::c_char; _UTX_USERSIZE],
  ...   |
  878 | |     }
  879 | | }
      | |_- similarly named struct `statvfs` defined here
```

I don't have access to a native NetBSD system, but Github Actions support this target - I have one set up like this:
https://github.com/woelper/oculante/blob/e6e54253ff7de22601678eb6aaebe3f84a02c7ca/.github/workflows/netbsd_minimal.yml

**Comment by Byron** [comment] 2023-09-17 08:40
Thanks for letting us know, and for suggesting how to setup CI. A contributor could probably start with setting up CI, reproduce this issue, and then make it pass by using the differently named symbols instead.

**Comment by 0323pin** [comment] 2023-09-17 20:26
It was brought to my attention that `statfs` is the old version of `statvfs`, which NetBSD does support and which, seems to be in the `libc` crate.
So, I've tried the [following patch](https://github.com/0323pin/trash-rs/commit/aee3dceac5575e4a2a23633ec5f3da5da79d9e89)

Unfortunately, now I get another error 😞 

```
~> cargo build --release
    Updating crates.io index
  Downloaded tinyvec_macros v0.1.1
  Downloaded scopeguard v1.2.0
  Downloaded form_urlencoded v1.2.0
  Downloaded iana-time-zone v0.1.57
  Downloaded log v0.4.20
  Downloaded percent-encoding v2.3.0
  Downloaded autocfg v1.1.0
  Downloaded unicode-bidi v0.3.13
  Downloaded once_cell v1.18.0
  Downloaded num-traits v0.2.16
  Downloaded url v2.4.1
  Downloaded chrono v0.4.31
  Downloaded tinyvec v1.6.0
  Downloaded unicode-normalization v0.1.22
  Downloaded idna v0.4.0
  Downloaded libc v0.2.148
  Downloaded 16 crates (1.7 MB) in 1.26s
   Compiling autocfg v1.1.0
   Compiling tinyvec_macros v0.1.1
   Compiling libc v0.2.148
   Compiling unicode-bidi v0.3.13
   Compiling tinyvec v1.6.0
   Compiling num-traits v0.2.16
   Compiling percent-encoding v2.3.0
   Compiling form_urlencoded v1.2.0
   Compiling unicode-normalization v0.1.22
   Compiling iana-time-zone v0.1.57
   Compiling idna v0.4.0
   Compiling chrono v0.4.31
   Compiling once_cell v1.18.0
   Compiling url v2.4.1
   Compiling scopeguard v1.2.0
   Compiling log v0.4.20
   Compiling trash v3.0.6 (/home/pin/Git/trash-rs)
error[E0425]: cannot find function `getmntinfo` in crate `libc`
   --> src/freedesktop.rs:706:32
    |
706 |     let count = unsafe { libc::getmntinfo(&mut fs_infos, libc::MNT_WAIT) };
    |                                ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MNT_WAIT` in crate `libc`
   --> src/freedesktop.rs:706:64
    |
706 |     let count = unsafe { libc::getmntinfo(&mut fs_infos, libc::MNT_WAIT) };
    |                                                                ^^^^^^^^ not found in `libc`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `trash` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Exception: cargo exited with 101
```

Thoughts?!

**Comment by wravoc** [comment] 2023-09-17 22:11
Not meaning to sidetrack here, but add some voice for additional targets. It is the same situation on Dragonfly BSD that any cargo that requires trash will not work failing on `get_mount_points`.

**Comment by 0323pin** [comment] 2023-09-18 07:37
I've now successfully built `trash-rs` on NetBSD, https://github.com/Byron/trash-rs/pull/84#issuecomment-1722890648

**Comment by 0323pin** [comment] 2023-09-25 14:52
@wravoc could we get the exact error? You wrote, `get_mount_points` and [my PR](https://github.com/Byron/trash-rs/pull/84) is waiting on it.

Now, I don't see such call on DragonFly BSD man pages but, I do see [`getmntinfo`](https://leaf.dragonflybsd.org/cgi/web-man?command=getmntinfo&section=ANY) just like in NetBSD.

Perhaps you could submit a similar pull request with rust-lang/libc adding the required function for it to build on DragonFly, After all, it too supports [`statvfs`](https://leaf.dragonflybsd.org/cgi/web-man?command=statvfs&section=ANY)

**Comment by wravoc** [comment] 2023-09-28 06:10
@0323pin 
So today, I have a more robust build of Dragonfly BSD or maybe your fix was merged and also fixed DF, or the compilation order has changed because I cannot replicate that issue any longer and I cannot just install 'trash 3.0.6' to test. I originally encountered that error as a dependency of "Nu [Shell] but now it is failing on something different.

Ok, I went to crates.io and looked up *dependents of* and installed the first binary that required 'trash' and this is the error.

```
   Compiling trash v3.0.1
error[E0425]: cannot find function `get_mount_points` in this scope
  --> /home/elias/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-3.0.1/src/freedesktop.rs:31:28
   |
31 |         let mount_points = get_mount_points()?;
   |                            ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_mount_points` in this scope
  --> /home/elias/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-3.0.1/src/freedesktop.rs:80:24
   |
80 |     let mount_points = get_mount_points()?;
   |                        ^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `trash` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dua-cli v2.20.1`, intermediate artifacts can be found at `/tmp/cargo-install3qZFpP`:
```

**Comment by 0323pin** [comment] 2023-09-28 06:51
@wravoc 

> So today, I have a more robust build of Dragonfly BSD or maybe your fix was merged and also fixed DF, or the compilation order has changed because I cannot replicate that issue any longer

Nothing has changed, none of my PRs have been merged, this one is still open and, I made a mistake on my `libc` PR and closed it, [Resubmitted yesterday](https://github.com/rust-lang/libc/pull/3368), now without rough edges.

I don't know DF but, dig through the headers (see my `libc` PR) and see what you are missing in [libc](https://github.com/rust-lang/libc/blob/main/src/unix/bsd/freebsdlike/dragonfly/mod.rs).

If you just want to build `nu` you can do it with `cargo build --release --no-default-features --features plugin,which-support,sqlite`. But, I guess you already know that.

**Comment by 0323pin** [comment] 2023-09-29 19:48
The libc bits have been [merged](https://github.com/rust-lang/libc/pull/3368#issuecomment-1741325520)

**Comment by 0323pin** [comment] 2023-10-01 17:27
@wravoc Please see: https://github.com/Byron/trash-rs/pull/84#issuecomment-1742115801

**Closed** 2023-10-08 07:00 UTC
Labels: enhancement, help wanted

**Comment by woelper** [comment] 2023-10-08 20:05
I just wanted to stop by and say a big **thanks** for fixing this!
